"""
Django settings for KalFIT project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
#
import os, dj_database_url
from decouple   import Csv, config
from unipath    import Path
#
PROJECT_DIR = Path(__file__).parent
#
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY      = 'n!mewg=m*md&2!)6u=dj^klqjpit56(^f55$@gq@1a1(-@n++*'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG           = True
ALLOWED_HOSTS   = ['*']
#
#
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'static_sitemaps',
    'authentication',
    'alimentation',
    'KalFIT',
    'api',
    'frontend',
    'django_extensions',
    'ws4redis',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
#
#
ROOT_URLCONF = 'KalFIT.urls'
#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ws4redis.context_processors.default', 
           ],
        },
    },
]
#
#WSGI_APPLICATION = 'KalFIT.wsgi.application'
##########################################
#
#   DJANGO WEBSOCKET REDIS
#
##########################################
#
WEBSOCKET_URL               = '/ws/'
WS4REDIS_EXPIRE             = 7200
WS4REDIS_PREFIX             = 'ws'
WSGI_APPLICATION            = 'ws4redis.django_runserver.application'
#WS4REDIS_HEARTBEAT          = '--heartbeat--'
#
# CELERY SETTINGS
BROKER_URL                  = 'redis://localhost:6379'
CELERY_BROKER_URL           = 'redis://localhost:6379'
CELERY_RESULT_BACKEND       = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT       = ['application/json']
CELERY_TASK_SERIALIZER      = 'json'
CELERY_RESULT_SERIALIZER    = 'json'
#
#
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#
SECRET_KEY = config('SECRET_KEY')
#
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = config('DEBUG', default=False, cast=bool)
#
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:////{0}'.format(os.path.join(BASE_DIR, 'db.sqlite3'))
    )
}
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
#
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
#
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOCALE_PATHS = (PROJECT_DIR.child('locale'), )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/

STATIC_ROOT 		    = PROJECT_DIR.parent.child('staticfiles')
STATIC_URL		        = '/static/'
STATICFILES_STORAGE 	= 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS        = (
    PROJECT_DIR.child('static'),
)
#
MEDIA_ROOT  = PROJECT_DIR.parent.child('media')
MEDIA_URL   = '/media/'
#
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
#
LANGUAGE_CODE   = 'en-us'
#
TIME_ZONE       = 'UTC'
#
USE_I18N        = True
#
USE_L10N        = True
#
USE_TZ          = True
ALLOWED_SIGNUP_DOMAINS = ['*']

FILE_UPLOAD_TEMP_DIR = '/tmp/'
FILE_UPLOAD_PERMISSIONS = 0o644
#
TAGGIT_CASE_INSENSITIVE = True
#
#
# Configure Django App for Heroku.
#import django_heroku
#django_heroku.settings(locals())
