# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-04 08:16
from __future__ import unicode_literals

import alimentation.models.alimentation
import alimentation.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('recipe', models.ImageField(blank=True, default='/media/alimentation/img.jpg', null=True, storage=alimentation.utils.OverwriteStorage(), upload_to=alimentation.models.alimentation.upload_image)),
                ('kcal', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('satured_fat', models.IntegerField(default=0)),
                ('unsatured_fat', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alimentation',
                'verbose_name': 'Alimentation',
                'verbose_name_plural': 'Alimentations',
            },
        ),
    ]
