# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-04 08:27
from __future__ import unicode_literals

import alimentation.models.alimentation
import alimentation.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='image',
            field=models.ImageField(blank=True, default='/media/alimentation/img.jpg', null=True, storage=alimentation.utils.OverwriteStorage(), upload_to=alimentation.models.alimentation.upload_image),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='recipe',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
