# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0002_auto_20180804_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
