# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-05 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0003_auto_20180804_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='satured_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='unsatured_fat',
            field=models.FloatField(default=0),
        ),
    ]
