# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0004_auto_20180805_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentation',
            name='recipe',
            field=models.TextField(),
        ),
    ]
